### ISSUE TITLE
Can't install with modern versions of fluentd

### ISSUE THREAD

**Issue by pavdmyt** [chaeyk/fluent-plugin-add-uuid#1]
Trying `gem install fluent-plugin-add-uuid` in container running on top of `gcr.io/google-containers/fluentd-elasticsearch:v2.4.0` image gives the following error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-add-uuid:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/strptime-0.1.9/ext/strptime
/usr/bin/ruby2.3 -r ./siteconf20200617-7-1gwjzaf.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
```

The abovementioned image is built using the following [Dockerfile](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile). I believe the issue can be fixed if update runtime dependency version constraint to something like this: `spec.add_runtime_dependency "fluentd", ">= 0.12", "< 2"`.

Is it possible to make new release with this fix?

**Comment by pavdmyt** [comment]
@chaeyk any chance to look at this?

**Comment by pavdmyt** [comment]
It comes out that `fluent-plugin-elasticsearch` supports generation of uniq ID via [elasticsearch_genid](https://github.com/uken/fluent-plugin-elasticsearch#generate-hash-id) filter.

Here is more [details](https://medium.com/redbox-techblog/tuning-fluentd-retries-avoiding-duplicate-documents-in-elasticsearch-e7cb9630a453) and why it may be preferable over [fluent-plugin-genhashvalue](https://github.com/mtakemi/fluent-plugin-genhashvalue).

**Comment by chaeyk** [comment]
@pavdmyt Error occured because development tools/headers were not installed.
You can install plugin with following commands.

> apt update && apt install ruby2.3-dev gcc make
> gem install fluent-plugin-add-uuid

Sorry, my reply was too late.
